import type { Config, Context } from '@netlify/functions';
import { getStore } from '@netlify/blobs';
import { checkRateLimit, type RateLimitResult } from './_shared/rate-limit.ts';
import { updateJSON } from './_shared/atomic-json.ts';
import { getClientIp, rateLimitKey } from './_shared/client-ip.ts';
import { EMBED_FIELD_VALUE_MAX, EMBED_TITLE_MAX, postWebhook, truncate } from './_shared/discord.ts';
// Generated by scripts/gen-post-slugs.mjs (runs before build / dev:netlify).
import postSlugs from './_shared/post-slugs.json' with { type: 'json' };

export const config: Config = {
	path: '/api/comments',
};

type Comment = {
	id: string;
	name: string;
	content: string;
	createdAt: string;
};

const MAX_NAME_LENGTH = 60;
const MAX_CONTENT_LENGTH = 2000;
const MAX_LINKS = 2;
const MAX_COMMENTS_PER_POST = 500;

const knownSlugs = new Set<string>(postSlugs);

function countLinks(text: string): number {
	return (text.match(/https?:\/\//gi) ?? []).length;
}

export default async (req: Request, context: Context) => {
	const url = new URL(req.url);
	const slug = url.searchParams.get('slug');

	if (!slug) {
		return Response.json({ error: 'Missing slug' }, { status: 400 });
	}

	const commentsStore = getStore({ name: 'comments' });

	if (req.method === 'GET') {
		const comments = ((await commentsStore.get(slug, { type: 'json' })) as Comment[] | null) ?? [];
		return Response.json({ comments });
	}

	if (req.method === 'POST') {
		// Only published posts get a comment key; anything else would create unbounded junk keys.
		if (!knownSlugs.has(slug)) {
			return Response.json({ error: 'Unknown post' }, { status: 404 });
		}

		let body: { name?: unknown; content?: unknown; website?: unknown } | null;
		try {
			body = await req.json();
		} catch {
			return Response.json({ error: 'Invalid JSON body' }, { status: 400 });
		}
		if (typeof body !== 'object' || body === null) {
			return Response.json({ error: 'Invalid JSON body' }, { status: 400 });
		}

		const { name, content, website } = body;

		// Honeypot field is hidden from real users via CSS; bots that fill every field trip it.
		if (website) {
			return Response.json({ error: '請手動輸入' }, { status: 400 });
		}
		if (typeof name !== 'string' || typeof content !== 'string' || !name.trim() || !content.trim()) {
			return Response.json({ error: 'Missing name or content' }, { status: 400 });
		}
		if (name.length > MAX_NAME_LENGTH) {
			return Response.json({ error: 'Name too long' }, { status: 400 });
		}
		if (content.length > MAX_CONTENT_LENGTH) {
			return Response.json({ error: 'Content too long' }, { status: 400 });
		}
		if (countLinks(content) > MAX_LINKS) {
			return Response.json({ error: 'Too many links' }, { status: 400 });
		}

		// Reserve the rate-limit slot before any side effect. The conditional write means
		// concurrent requests from one client can't all read the same "under the limit" state.
		const now = Date.now();
		const createdAt = new Date(now).toISOString();
		const rateLimitStore = getStore({ name: 'comment-rate-limits' });
		const reservation = await updateJSON<{ timestamps: string[] }, RateLimitResult>(
			rateLimitStore,
			rateLimitKey(getClientIp(req, context)),
			(current) => {
				const result = checkRateLimit(current?.timestamps ?? [], now);
				if (result.limited) return { skip: result };
				return { write: { timestamps: [...result.recentTimestamps, createdAt] }, value: result };
			},
		);

		if (reservation.status !== 'written') {
			return Response.json(
				{
					error: 'Too many comments, please wait before posting again',
					...(reservation.status === 'skipped' && reservation.value.limited
						? { retryAfterSeconds: reservation.value.retryAfterSeconds }
						: {}),
				},
				{ status: 429 },
			);
		}

		const comment: Comment = {
			id: `c_${crypto.randomUUID()}`,
			name: name.trim().slice(0, MAX_NAME_LENGTH),
			content: content.trim().slice(0, MAX_CONTENT_LENGTH),
			createdAt,
		};

		// Conditional append: a concurrent post or admin delete on the same post can't be
		// overwritten by a stale copy of the array.
		const appended = await updateJSON<Comment[], 'ok' | 'full'>(commentsStore, slug, (current) => {
			const existing = current ?? [];
			if (existing.length >= MAX_COMMENTS_PER_POST) return { skip: 'full' };
			return { write: [...existing, comment], value: 'ok' };
		});

		if (appended.status === 'skipped') {
			return Response.json({ error: 'This post is not accepting more comments' }, { status: 409 });
		}
		if (appended.status === 'conflict') {
			return Response.json({ error: 'Busy, please try again' }, { status: 503 });
		}

		const webhookUrl = process.env.DISCORD_WEBHOOK_URL;
		if (webhookUrl) {
			// waitUntil keeps this fetch alive after the response is returned; a bare
			// un-awaited fetch can get cut off when Netlify freezes the container.
			context.waitUntil(
				postWebhook(
					webhookUrl,
					{
						embeds: [
							{
								title: truncate(`💬 新留言 — ${slug}`, EMBED_TITLE_MAX),
								url: `${url.origin}/blog/${encodeURIComponent(slug)}`,
								color: 0xf6ad55,
								fields: [
									{ name: '留言者', value: comment.name, inline: true },
									{
										name: '時間',
										value: new Date(comment.createdAt).toLocaleString('zh-TW', {
											timeZone: 'Asia/Taipei',
										}),
										inline: true,
									},
									// The full comment is stored, so a truncated preview is enough here.
									{ name: '內容', value: truncate(comment.content, EMBED_FIELD_VALUE_MAX) },
								],
							},
						],
					},
					'comments',
				),
			);
		}

		return Response.json({ comment }, { status: 201 });
	}

	return Response.json({ error: 'Method not allowed' }, { status: 405 });
};
